### ISSUE TITLE
FastaIO does not have precompilation enabled

### ISSUE THREAD

**Issue by tkelman** [diegozea/MIToS.jl#32]
ref https://github.com/carlobaldassi/FastaIO.jl/blob/master/src/FastaIO.jl

This is actually a prerequisite to using `__precompile__()` in your package, all of your dependencies have to have it enabled first. You've been getting away without it so far, but this will become noticeable very soon on 0.5 and 0.6-dev, where it might start causing errors.

**Comment by carlobaldassi** [comment]
This is now fixed in FastaIO v0.2.0. It's just a matter of updating the REQUIRE file.

**Comment by tkelman** [comment]
Right on.

**Comment by diegozea** [comment]
Thanks @carlobaldassi  & @tkelman !
