### ISSUE TITLE
Distributed Package imported in scripts but not in the REQUIRE file

### ISSUE THREAD

**Issue by javieriserte** [diegozea/MIToS.jl#49]

**Comment by diegozea** [comment]
Hi @javieriserte  😃 

I've tagged a new version using `Project.toml` instead of `REQUIRE` that should solve this problem.

Does it work now?

**Comment by javieriserte** [comment]
Yes, it did.

I made a fresh install of MIToS on the latest julia docker image on dockerhub. It works perfect.
