### ISSUE TITLE
404 error from function 'getpdbdescription'

### ISSUE THREAD

**Issue by kool7d** [diegozea/MIToS.jl#59]
I am getting a 404 error from function 'getpdbdescription'.

`
HTTP/1.1 404 Not Found
X-Powered-By: Express
Strict-Transport-Security: max-age=31536000000; includeSubDomains
Cache-Control: private, no-cache, max-age=0, must-revalidate
Content-Type: text/html; charset=utf-8
Content-Length: 39674
ETag: W/"9afa-t3cWyFWTs7aO0Iy60YWTWEN5EGo"
Vary: Accept-Encoding
Date: Thu, 31 Dec 2020 00:07:16 GMT
X-Backend-Server: 10.100.50.12

""")
in top-level scope at Scratch1.jl:302
in getpdbdescription at MIToS\IWuWP\src\PDB\PDBMLParser.jl:269
in #getpdbdescription#36 at MIToS\IWuWP\src\PDB\PDBMLParser.jl:269
in downloadpdbheader at MIToS\IWuWP\src\PDB\PDBMLParser.jl:244 
in #downloadpdbheader#35 at MIToS\IWuWP\src\PDB\PDBMLParser.jl:248
in download_file at MIToS\IWuWP\src\Utils\Read.jl:28 
in #download_file#3 at MIToS\IWuWP\src\Utils\Read.jl:28 
in open at HTTP\IAI92\src\HTTP.jl:348 
in #open#6 at HTTP\IAI92\src\HTTP.jl:348 
in request##kw at HTTP\IAI92\src\HTTP.jl:314 
in #request#4 at HTTP\IAI92\src\HTTP.jl:314
in  at HTTP\IAI92\src\RedirectRequest.jl:21
in #request#1 at HTTP\IAI92\src\RedirectRequest.jl:24
in  at HTTP\IAI92\src\BasicAuthRequest.jl:21
in #request#1 at HTTP\IAI92\src\BasicAuthRequest.jl:28
in request##kw at HTTP\IAI92\src\MessageRequest.jl:28 
in #request#1 at HTTP\IAI92\src\MessageRequest.jl:51
in  at HTTP\IAI92\src\RetryRequest.jl:31
in #request#1 at HTTP\IAI92\src\RetryRequest.jl:44 
in 56#58##kw at base\error.jl:284 
in  at base\error.jl:288
in  at HTTP\IAI92\src\ExceptionRequest.jl:19
in #request#1 at HTTP\IAI92\src\ExceptionRequest.jl:22`

**Comment by diegozea** [comment]
Hi! Thanks for pointing it out :) It looks like PDB has deprecated the old REST API: https://data.rcsb.org/migration-guide.html#pdb-file-description. I am looking up into updating it to the new one. I'll keep you posted.

**Comment by diegozea** [comment]
Hi! https://github.com/diegozea/MIToS.jl/commit/27f2c5b9fe66ae2bfb54a73679b5092529abdb11 should fix that. Note that the output structure has changed. I will publish a new version in a little with this update. Thanks again, Best
