### ISSUE TITLE
SIFTS download error

### ISSUE THREAD

**Issue by kool7d** [diegozea/MIToS.jl#63]
Here is the code first:
`sfile = downloadsifts("2VB1")`

I am getting this error:

`ERROR: ArgumentError: missing or unsupported scheme in URL (expected http(s) or ws(s)): ftp://ftp.ebi.ac.uk/pub/databases/msd/sifts/split_xml/vb/2vb1.xml.gz`

This happens with basically any of the stuff that requires downloading from ftp. Also I can't find their XML files, it's weird. Only JSON.

**Comment by diegozea** [comment]
Hi! 
Thanks for reporting this, and sorry for the delay. 
This is now solved by https://github.com/diegozea/MIToS.jl/commit/16e324762c858dd44e1d9e41fe1985f4fb5254c4 
The error will be fixed in the next minor release of the package.
Cheers!
